# Generated by Django 6.0.4 on 2026-06-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price_at_added',
            field=models.IntegerField(default=0),
        ),
    ]
