# Generated by Django 6.0.4 on 2026-07-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_sellerorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Menunggu Pembayaran'), ('paid', 'Sudah Dibayar'), ('failed', 'Pembayaran Gagal'), ('expired', 'Pembayaran Kedaluwarsa')], default='pending', max_length=20),
        ),
    ]
