# Generated by Django 6.0.4 on 2026-07-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Menunggu Pembayaran'), ('paid', 'Sudah Dibayar'), ('failed', 'Pembayaran Gagal'), ('expired', 'Pembayaran Kedaluwarsa'), ('canceled', 'Pesanan Dibatalkan')], default='pending', max_length=20),
        ),
    ]
