# Generated by Django 6.0.4 on 2026-07-16 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_order', 'New Order'), ('payment_success', 'Payment Success'), ('order_processed', 'Order Processed'), ('order_shipped', 'Order Shipped'), ('order_completed', 'Order Completed'), ('order_cancelled', 'Order Cancelled')], max_length=30),
        ),
    ]
