# Generated by Django 6.0.4 on 2026-07-16 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type'),
        ('orders', '0006_alter_sellerorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='seller_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.sellerorder'),
        ),
    ]
