# Generated by Django 6.0.4 on 2026-06-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_image_product_status_product_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('new', 'Baru'), ('used', 'Bekas')], default='new', max_length=10),
        ),
    ]
